# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ThirtyDaysOfReactNative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ThirtyDaysOfReactNative
# 但是如果你的结构不同，那你就要根据实际路径修改下面的`:path`
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'RCTText',
  'RCTNetwork',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTPushNotification',
  'RCTActionSheet',
  'RCTGeolocation',
  'RCTSettings',
  'RCTVibration',
  'RCTAnimation’,  

  'RCTWebSocket', # 这个模块是用于调试功能的
  # 在这里继续添加你所需要的模块
  ]
  pod 'RNGL', :path => '../node_modules/gl-react-native'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-video', :path => '../node_modules/react-native-video'



  target 'ThirtyDaysOfReactNativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
